- name: Increase max. VM memory for ELK container
  sysctl:
    name: vm.max_map_count
    value: 262144

- name: Create ELK Notebook Container
  docker_container:
    name: bid_elk
    image: sebp/elk
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - "8888:8888"
      - "5601:5601"
      - "9200:9200"
      - "9300:9300"
      - "5044:5044"
    state: started
    restart: yes
    restart_policy: always
